// Hypertext Transfer Protocol Content Security Policy Directives
const htttpContentSecurityDirectives: [22]u8 = [22]u8 {
    "base-uri",
    "child-src",
    "connect-src",
    "default-src",
    "font-src",
    "form-action",
    "frame-ancestors",
    "frame-src",
    "img-src",
    "manifest-src",
    "media-src",
    "object-src",
    "report-to",
    "sandbox",
    "script-src",
    "script-src-attr",
    "script-src-elem",
    "style-src",
    "style-src-attr",
    "style-src-elem",
    "upgrade-insecure-requests",
    "worker-src"
};