// HTTP Headers
const httpHeaders: [145]u8 = [145]u8 {
    "Accept
    "Accept-CH
    "Accept-Charset
    "Accept-Encoding
    "Accept-Language
    "Accept-Patch
    "Accept-Post
    "Accept-Ranges
    "Access-Control-Allow-Credentials
    "Access-Control-Allow-Headers
    "Access-Control-Allow-Methods
    "Access-Control-Allow-Origin
    "Access-Control-Expose-Headers
    "Access-Control-Max-Age
    "Access-Control-Request-Headers
    "Access-Control-Request-Method
    "Age
    "Allow
    "Alt-Svc
    "Alt-Used
    "Attribution-Reporting-EligibleExperimental
    "Attribution-Reporting-Register-SourceExperimental
    "Attribution-Reporting-Register-TriggerExperimental
    "Authorization
    "Cache-Control
    "Clear-Site-Data
    "Connection
    "Content-DigestExperimental
    "Content-Disposition
    "Content-DPRNon-standardDeprecated
    "Content-Encoding
    "Content-Language
    "Content-Length
    "Content-Location
    "Content-Range
    "Content-Security-Policy
    "Content-Security-Policy-Report-Only
    "Content-Type
    "Cookie
    "Critical-CHExperimental
    "Cross-Origin-Embedder-Policy
    "Cross-Origin-Opener-Policy
    "Cross-Origin-Resource-Policy
    "Date
    "Device-Memory
    "DigestNon-standardDeprecated
    "DNTNon-standardDeprecated
    "DownlinkExperimental
    "DPRNon-standardDeprecated
    "Early-DataExperimental
    "ECTExperimental
    "ETag
    "Expect
    "Expect-CTDeprecated
    "Expires
    "Forwarded
    "From
    "Host
    "If-Match
    "If-Modified-Since
    "If-None-Match
    "If-Range
    "If-Unmodified-Since
    "Keep-Alive
    "Last-Modified
    "Link
    "Location
    "Max-Forwards
    "NELExperimental
    "No-Vary-SearchExperimental
    "Observe-Browsing-TopicsExperimentalNon-standard
    "Origin
    "Origin-Agent-ClusterExperimental
    "Permissions-Policy
    "PragmaDeprecated
    "Priority
    "Proxy-Authenticate
    "Proxy-Authorization
    "Range
    "Referer
    "Referrer-Policy
    "Refresh
    "Report-ToNon-standardDeprecated
    "Reporting-EndpointsExperimental
    "Repr-DigestExperimental
    "Retry-After
    "RTTExperimental
    "Save-DataExperimental
    "Sec-Browsing-TopicsExperimentalNon-standard
    "Sec-CH-Prefers-Color-SchemeExperimental
    "Sec-CH-Prefers-Reduced-MotionExperimental
    "Sec-CH-Prefers-Reduced-TransparencyExperimental
    "Sec-CH-UAExperimental
    "Sec-CH-UA-ArchExperimental
    "Sec-CH-UA-BitnessExperimental
    "Sec-CH-UA-Full-VersionDeprecated
    "Sec-CH-UA-Full-Version-ListExperimental
    "Sec-CH-UA-MobileExperimental
    "Sec-CH-UA-ModelExperimental
    "Sec-CH-UA-PlatformExperimental
    "Sec-CH-UA-Platform-VersionExperimental
    "Sec-Fetch-Dest
    "Sec-Fetch-Mode
    "Sec-Fetch-Site
    "Sec-Fetch-User
    "Sec-GPCExperimentalNon-standard
    "Sec-Purpose
    "Sec-WebSocket-Accept
    "Sec-WebSocket-Extensions
    "Sec-WebSocket-Key
    "Sec-WebSocket-Protocol
    "Sec-WebSocket-Version
    "Server
    "Server-Timing
    "Service-Worker-Navigation-Preload
    "Set-Cookie
    "Set-LoginExperimental
    "SourceMap
    "Speculation-RulesExperimental
    "Strict-Transport-Security
    "Supports-Loading-ModeExperimental
    "TE
    "Timing-Allow-Origin
    "TkNon-standardDeprecated
    "Trailer
    "Transfer-Encoding
    "Upgrade
    "Upgrade-Insecure-Requests
    "User-Agent
    "Vary
    "Via
    "Viewport-WidthNon-standardDeprecated
    "Want-Content-DigestExperimental
    "Want-DigestNon-standardDeprecated
    "Want-Repr-DigestExperimental
    "WarningDeprecated
    "WidthNon-standardDeprecated
    "WWW-Authenticate
    "X-Content-Type-Options
    "X-DNS-Prefetch-ControlNon-standard
    "X-Forwarded-ForNon-standard
    "X-Forwarded-HostNon-standard
    "X-Forwarded-ProtoNon-standard
    "X-Frame-Options
    "X-XSS-ProtectionNon-standard
};